"use client";

import { useState } from "react";
import { Navbar } from "@/components/navbar";
import { HeroSection } from "@/components/hero-section";
import { FeaturesSection } from "@/components/features-section";
import { FileUpload } from "@/components/file-upload";
import { QuestionForm } from "@/components/question-form";
import { AnswerDisplay } from "@/components/answer-display";
import { Footer } from "@/components/footer";
import { toast } from "sonner";
import { motion } from "framer-motion";

export default function Home() {
  const [file, setFile] = useState<File | null>(null);
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleFileUpload = (uploadedFile: File) => {
    setFile(uploadedFile);
    // Reset previous Q&A when a new file is uploaded
    setQuestion("");
    setAnswer("");
  };

  const handleAskQuestion = async (questionText: string) => {
    setIsLoading(true);
    setQuestion(questionText);
    
    try {
      // Simulate API call to backend
      // In a real implementation, this would be a fetch to your FastAPI backend
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Mock response - this would come from your backend in a real implementation
      const mockAnswer = `Based on the document "${file?.name}", the answer to your question "${questionText}" is:
      
This is a simulated answer that would be generated by your FastAPI backend. The actual implementation would analyze the document content and provide a relevant answer based on the question asked.

The document-based question answering system would:
1. Process the uploaded document
2. Understand the context and content
3. Interpret your question
4. Generate a precise answer from the document's information

In a production environment, this would leverage natural language processing and machine learning to extract the most relevant information from your document.`;
      
      setAnswer(mockAnswer);
      toast.success("Answer generated successfully!");
    } catch (error) {
      console.error("Error processing question:", error);
      toast.error("Failed to process your question. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />
      
      <main className="flex-1">
        <HeroSection />
        
        <section id="upload-section" className="py-16">
          <div className="container">
            <div className="mx-auto max-w-3xl">
              <motion.div
                initial={{ opacity: 0 }}
                whileInView={{ opacity: 1 }}
                transition={{ duration: 0.5 }}
                viewport={{ once: true }}
                className="text-center mb-10"
              >
                <h2 className="text-3xl font-bold tracking-tight mb-4">
                  Upload Your Document
                </h2>
                <p className="text-muted-foreground">
                  Upload a document and ask questions to get instant answers.
                </p>
              </motion.div>
              
              <div className="space-y-8">
                <FileUpload onFileUpload={handleFileUpload} />
                
                <QuestionForm 
                  onAskQuestion={handleAskQuestion} 
                  isFileUploaded={!!file}
                />
                
                {question && answer && (
                  <AnswerDisplay 
                    question={question} 
                    answer={answer}
                  />
                )}
              </div>
            </div>
          </div>
        </section>
        
        <FeaturesSection />
      </main>
      
      <Footer />
    </div>
  );
}